# Generated by Django 5.1.7 on 2025-03-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("espece", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("nom_latin", models.CharField(max_length=100)),
                ("famille", models.CharField(max_length=100)),
                ("taille", models.TextField()),
                ("region", models.TextField()),
                ("habitat", models.TextField()),
                ("fun_fact", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="animal_images/"
                    ),
                ),
                (
                    "empreinte",
                    models.ImageField(
                        blank=True, null=True, upload_to="animal_tracks/"
                    ),
                ),
            ],
        ),
    ]
