# Generated by Django 4.2.20 on 2025-04-15 19:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wildlenswebui', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='empreinte',
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField()),
                ('image', models.ImageField(upload_to='analyses-images/images/')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='wildlenswebui.animal')),
            ],
            options={
                'verbose_name': 'Analyse',
                'verbose_name_plural': 'Analyses',
            },
        ),
    ]
