# Generated by Django 4.2.20 on 2025-06-05 14:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("confidence", models.FloatField()),
                ("image", models.ImageField(upload_to="analyses-images/images/")),
            ],
            options={
                "verbose_name": "Analyse",
                "verbose_name_plural": "Analyses",
            },
        ),
        migrations.RenameField(
            model_name="animal",
            old_name="name",
            new_name="espece",
        ),
        migrations.RemoveField(
            model_name="animal",
            name="date_seen",
        ),
        migrations.RemoveField(
            model_name="animal",
            name="location",
        ),
        migrations.RemoveField(
            model_name="animal",
            name="species",
        ),
        migrations.RemoveField(
            model_name="animal",
            name="user",
        ),
        migrations.AddField(
            model_name="animal",
            name="description",
            field=models.TextField(default="Aucune description disponible."),
        ),
        migrations.AddField(
            model_name="animal",
            name="famille",
            field=models.CharField(default="Mammifère", max_length=100),
        ),
        migrations.AddField(
            model_name="animal",
            name="fun_fact",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="habitat",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="nom_latin",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="region",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="taille",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="animal",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="animal_images/"),
        ),
        migrations.DeleteModel(
            name="Species",
        ),
        migrations.AddField(
            model_name="analysis",
            name="animal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analyses",
                to="api.animal",
            ),
        ),
    ]
